export const mockUsers = [
    {
        id: '1',
        email: 'admin@kfupm.edu.sa',
        name: 'Admin User',
        role: 'admin',
    },
    {
        id: '2',
        email: 's201900001@kfupm.edu.sa',
        name: 'Ahmed Al-Otaibi',
        role: 'student',
        studentId: '201900001',
    },
    {
        id: '3',
        email: 'maintenance@kfupm.edu.sa',
        name: 'Mohammed Al-Mansour',
        role: 'maintenance_staff',
    },
];
export const mockLocations = [
    {
        id: 'loc1',
        name: 'Building 22 (Computer Science)',
        category: 'academic',
        coordinates: { x: 800, y: 700 },
        buildingShape: { width: 80, height: 60 },
        description: 'Computer Science and Engineering Department. Home to cutting-edge research labs and modern classrooms.',
        openHours: '7:00 AM - 9:00 PM',
        amenities: ['Computer Labs', 'Study Areas', 'Faculty Offices', 'Auditorium'],
        services: [
            { name: 'IT Support Desk', hours: '8:00 AM - 4:00 PM' },
            { name: 'Student Advising', hours: '9:00 AM - 3:00 PM' },
            { name: 'Printing Services', hours: '7:30 AM - 8:00 PM' },
        ],
        facilities: {
            labs: ['Computer Lab 1', 'Computer Lab 2', 'AI Research Lab', 'Networking Lab'],
            printers: 12,
            prayerRooms: 2,
            bathrooms: 8,
            studyRooms: 6,
        },
    },
    {
        id: 'loc2',
        name: 'Building 5 (Mathematics)',
        category: 'academic',
        coordinates: { x: 535, y: 460 },
        buildingShape: { width: 70, height: 55 },
        description: 'Mathematics Department with lecture halls and tutorial rooms.',
        openHours: '7:00 AM - 8:00 PM',
        amenities: ['Lecture Halls', 'Tutorial Rooms', 'Faculty Offices'],
        facilities: {
            labs: ['Mathematics Lab'],
            printers: 6,
            prayerRooms: 1,
            bathrooms: 6,
            studyRooms: 4,
        },
    },
    {
        id: 'loc3',
        name: 'Building 9 (Petroleum Engineering)',
        category: 'academic',
        coordinates: { x: 900, y: 700 },
        buildingShape: { width: 90, height: 70 },
        description: 'Petroleum Engineering Department with specialized labs and research facilities.',
        openHours: '7:00 AM - 9:00 PM',
        amenities: ['Research Labs', 'Simulation Centers', 'Faculty Offices'],
        facilities: {
            labs: ['Petroleum Lab', 'Drilling Simulation Lab', 'Research Lab 1', 'Research Lab 2'],
            printers: 8,
            prayerRooms: 2,
            bathrooms: 10,
            studyRooms: 5,
        },
    },
    {
        id: 'loc4',
        name: 'King Fahd Central Library',
        category: 'library',
        coordinates: { x: 610, y: 560 },
        buildingShape: { width: 120, height: 80 },
        description: 'Main university library with extensive collection and study spaces.',
        openHours: '8:00 AM - 12:00 AM',
        capacity: 2000,
        amenities: ['Reading Rooms', 'Computer Labs', 'Group Study Rooms', 'Silent Study Areas'],
        facilities: {
            labs: ['Computer Lab'],
            printers: 20,
            prayerRooms: 3,
            bathrooms: 12,
            studyRooms: 15,
        },
    },
    {
        id: 'loc5',
        name: 'Student Center Cafeteria',
        category: 'restaurant',
        coordinates: { x: 250, y: 450 },
        buildingShape: { width: 85, height: 50 },
        description: 'Main cafeteria offering variety of meals and dining options.',
        openHours: '6:00 AM - 11:00 PM',
        amenities: ['Indoor Seating', 'Outdoor Terrace', 'Multiple Cuisines'],
        facilities: {
            printers: 2,
            prayerRooms: 1,
            bathrooms: 6,
        },
    },
    {
        id: 'loc6',
        name: 'Starbucks',
        category: 'cafe',
        coordinates: { x: 150, y: 350 },
        buildingShape: { width: 40, height: 35 },
        description: 'Coffee shop with beverages and light snacks.',
        openHours: '7:00 AM - 10:00 PM',
        facilities: {
            bathrooms: 2,
        },
    },
    {
        id: 'loc7',
        name: 'Dhahran Cafe',
        category: 'cafe',
        coordinates: { x: 650, y: 500 },
        buildingShape: { width: 45, height: 35 },
        description: 'Campus cafe offering coffee, tea, and pastries.',
        openHours: '7:00 AM - 9:00 PM',
        facilities: {
            bathrooms: 2,
        },
    },
    {
        id: 'loc8',
        name: 'Dorm 1',
        category: 'dorm',
        coordinates: { x: 850, y: 880 },
        buildingShape: { width: 100, height: 90 },
        description: 'Undergraduate student dormitory with modern facilities.',
        capacity: 500,
        amenities: ['Common Rooms', 'Study Lounges', 'Prayer Room', 'Laundry'],
        facilities: {
            printers: 4,
            prayerRooms: 2,
            bathrooms: 30,
            studyRooms: 8,
        },
    },
    {
        id: 'loc9',
        name: 'Dorm 5',
        category: 'dorm',
        coordinates: { x: 520, y: 210 },
        buildingShape: { width: 100, height: 90 },
        description: 'Graduate student dormitory.',
        capacity: 400,
        amenities: ['Study Lounges', 'Prayer Room', 'Laundry', 'Gym'],
        facilities: {
            printers: 3,
            prayerRooms: 2,
            bathrooms: 25,
            studyRooms: 6,
        },
    },
    {
        id: 'loc10',
        name: 'Parking Lot A',
        category: 'parking',
        coordinates: { x: 150, y: 250 },
        buildingShape: { width: 80, height: 40 },
        description: 'Main parking facility near academic buildings.',
        capacity: 300,
    },
    {
        id: 'loc11',
        name: 'Parking Lot B',
        category: 'parking',
        coordinates: { x: 700, y: 400 },
        buildingShape: { width: 70, height: 40 },
        description: 'Parking near dormitories.',
        capacity: 200,
    },
    {
        id: 'loc12',
        name: 'Sports Complex',
        category: 'sports',
        coordinates: { x: 800, y: 500 },
        buildingShape: { width: 110, height: 75 },
        description: 'Multi-purpose sports facility with gym and courts.',
        openHours: '6:00 AM - 11:00 PM',
        amenities: ['Gym', 'Basketball Courts', 'Swimming Pool', 'Tennis Courts'],
        facilities: {
            prayerRooms: 2,
            bathrooms: 8,
        },
    },
];
export const mockStories = [
    {
        id: 'story1',
        userId: '2',
        userName: 'Ahmed Al-Otaibi',
        locationId: 'loc1',
        title: 'Late night coding session',
        text: 'Spent all night here working on my senior project. The Computer Lab 2 is amazing! Met my best friends here during our first semester.',
        likes: ['1', '3'],
        createdAt: '2024-01-25T10:30:00Z',
    },
    {
        id: 'story2',
        userId: '1',
        userName: 'Sara Al-Ahmed',
        locationId: 'loc1',
        title: 'First day memories',
        text: 'I still remember my first day in this building. I was so nervous but the seniors were very helpful. This place holds a special place in my heart.',
        likes: ['2'],
        createdAt: '2024-01-20T14:15:00Z',
    },
    {
        id: 'story3',
        userId: '2',
        userName: 'Ahmed Al-Otaibi',
        locationId: 'loc4',
        title: 'My favorite study spot',
        text: 'The 3rd floor study room is my go-to place before exams. Quiet, peaceful, and great atmosphere for deep focus. Highly recommend!',
        likes: ['1', '3'],
        createdAt: '2024-01-22T09:00:00Z',
    },
    {
        id: 'story4',
        userId: '3',
        userName: 'Khaled Al-Rashid',
        locationId: 'loc5',
        title: 'Best shawarma on campus',
        text: 'The shawarma here is legendary! Every Friday after class, we come here with friends. Good food, good vibes.',
        likes: ['2'],
        createdAt: '2024-01-23T12:30:00Z',
    },
    {
        id: 'story5',
        userId: '1',
        userName: 'Sara Al-Ahmed',
        locationId: 'loc8',
        title: 'Home away from home',
        text: 'Living here for 3 years now. Made lifelong friends and countless memories. The study lounge on the 2nd floor is where we pull all-nighters together!',
        likes: ['2', '3'],
        createdAt: '2024-01-21T20:45:00Z',
    },
];
export const mockBusRoutes = [
    {
        id: 'route1',
        name: 'Main Campus Loop',
        stops: [
            { id: 'stop1', name: 'Library', coordinates: { x: 400, y: 380 }, arrivalTimes: ['7:00', '7:30', '8:00'] },
            { id: 'stop2', name: 'Dorms', coordinates: { x: 200, y: 550 }, arrivalTimes: ['7:15', '7:45', '8:15'] },
            { id: 'stop3', name: 'Engineering', coordinates: { x: 550, y: 300 }, arrivalTimes: ['7:30', '8:00', '8:30'] },
        ],
        color: '#FF6B6B',
        path: [
            { x: 400, y: 380 },
            { x: 300, y: 450 },
            { x: 200, y: 550 },
            { x: 400, y: 500 },
            { x: 550, y: 300 },
            { x: 400, y: 380 },
        ],
    },
];
export const mockMainPaths = [
    {
        id: 'path1',
        name: 'Academic Corridor',
        description: 'Main pathway connecting academic buildings',
        path: [
            { x: 300, y: 250 },
            { x: 450, y: 200 },
            { x: 550, y: 300 },
        ],
        color: '#4A90E2',
    },
    {
        id: 'path2',
        name: 'Central Path',
        description: 'Central walkway through campus',
        path: [
            { x: 200, y: 200 },
            { x: 400, y: 350 },
            { x: 600, y: 500 },
        ],
        color: '#50C878',
    },
];
export const mockComplaints = [
    {
        id: 'comp1',
        userId: '2',
        userName: 'Ahmed Al-Otaibi',
        locationId: 'loc1',
        locationName: 'Building 22 (Computer Science)',
        category: 'Facility Issue',
        description: 'Air conditioning not working in Computer Lab 2',
        status: 'in_progress',
        assignedTo: '3',
        notes: 'Technician dispatched',
        createdAt: '2024-01-28T10:00:00Z',
        updatedAt: '2024-01-28T14:00:00Z',
    },
];
export const mockComments = [
    {
        id: 'comment1',
        userId: '2',
        userName: 'Ahmed Al-Otaibi',
        locationId: 'loc1',
        text: 'Great facilities and very well maintained. The computer labs are top-notch!',
        rating: 5,
        createdAt: '2024-01-25T09:30:00Z',
    },
];
export const mockAnnouncements = [
    {
        id: 'ann1',
        title: 'Library Extended Hours During Finals',
        content: 'The King Fahd Central Library will be open 24/7 during the final exam period (Week 15-16).',
        category: 'academic',
        date: '2024-01-28',
        priority: 'high',
    },
    {
        id: 'ann2',
        title: 'New Cafe Opening',
        content: 'A new cafe will be opening next to Building 5. Grand opening on February 1st!',
        category: 'general',
        date: '2024-01-27',
        priority: 'low',
    },
];
